name: Build AutoFillApp EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # đổi đúng version project của bạn

      - name: Restore dependencies
        run: dotnet restore AutoFillApp.csproj

      - name: Build
        run: dotnet build AutoFillApp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish AutoFillApp.csproj -c Release -r win-x64 --self-contained true -o ./publish

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoFillApp_EXE
          path: ./publish
