name: Build AutoFillApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish single file exe
      run: dotnet publish AutoFillApp.csproj -c Release -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -o publish

    - name: Copy extra files
      run: |
        copy profiles.json publish\
        echo @echo off > publish\RunApp.bat
        echo AutoFillApp.exe >> publish\RunApp.bat
        echo pause >> publish\RunApp.bat

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoFillApp_EXE
        path: publish
